// ========================================
// MOCK: Earnings - Sistema de Cotas Ciano
// ========================================

export type BonusType =
  | 'firstPurchase'
  | 'repurchase'
  | 'team'
  | 'leadership'
  | 'dividend';

export interface EarningEntry {
  id: string;
  userId: string;
  bonusType: BonusType;
  amount: number;
  sourceUserId: string | null; // Who generated this bonus
  sourceUserName: string | null;
  description: string;
  level: number; // Network level (1 = direct, 2-5 = indirect)
  referenceMonth: string; // YYYY-MM
  status: 'pending' | 'paid' | 'cancelled';
  createdAt: string;
  paidAt: string | null;
  /**
   * Whether this earning falls within the eligible cutoff window.
   * Rule: the purchase that generated this earning must have occurred
   * on or before the last day of the month prior to referenceMonth.
   * If false, the earning will be paid in the following month's cycle.
   */
  cutoffEligible: boolean;
}

export interface MonthlyEarningSummary {
  month: string;
  userId: string;
  firstPurchase: number;
  repurchase: number;
  team: number;
  leadership: number;
  dividend: number;
  total: number;
  lossProjection: number; // Amount that would be lost if user doesn't qualify
  /**
   * Earnings from the network: firstPurchase + repurchase + team + leadership.
   * These are bonuses generated by quota purchases by the user's downlines.
   */
  networkEarnings: number;
  /**
   * Earnings from quotas: dividends only.
   * Calculated as: (lodgeProfitPool × userQuotas) / totalQuotas.
   */
  quotaEarnings: number;
  /**
   * Last day of the month prior to `month`. Purchases after this date
   * only qualify for the following month's payout.
   */
  cutoffDate: string; // YYYY-MM-DD
}

export interface UserEarningsOverview {
  userId: string;
  totalEarned: number;
  pendingEarnings: number;
  thisMonthEarnings: number;
  lastMonthEarnings: number;
  averageMonthly: number;
  lossProjection: number; // Current potential loss
}

// ─── Cutoff utilities ───────────────────────────────────────────

/**
 * Returns the cutoff date (last day of the month prior to referenceMonth)
 * as a YYYY-MM-DD string.
 *
 * Rule: to receive earnings for month X, a quota purchase must have
 * happened on or before this date. Purchases after this date only
 * count toward the NEXT month's payout.
 */
export function getCutoffDate(referenceMonth: string): string {
  const [y, m] = referenceMonth.split('-').map(Number) as [number, number];
  // Last day of the prior month = day 0 of the current month
  const lastDay = new Date(y, m - 1, 0);
  return lastDay.toISOString().slice(0, 10);
}

/**
 * Returns true if a purchase made on `purchaseDate` is AFTER the cutoff
 * for `referenceMonth`, meaning it only qualifies for the next month.
 */
export function isAfterCutoff(purchaseDate: string, referenceMonth: string): boolean {
  const cutoff = getCutoffDate(referenceMonth);
  return purchaseDate.slice(0, 10) > cutoff;
}

// Sample earnings ledger
export const mockEarnings: EarningEntry[] = [
  // User 002 - João Silva earnings
  {
    id: 'earn-001',
    userId: 'user-002',
    bonusType: 'firstPurchase',
    amount: 2500,
    sourceUserId: 'user-005',
    sourceUserName: 'Ana Costa',
    description: 'Bônus primeira compra - Compra de 25 cotas',
    level: 1,
    referenceMonth: '2024-02',
    status: 'paid',
    createdAt: '2024-02-20T09:20:00Z',
    paidAt: '2024-03-15T10:00:00Z',
    // Purchase happened 2024-02-20; cutoff for '2024-02' is 2024-01-31 → after cutoff
    cutoffEligible: false,
  },
  {
    id: 'earn-002',
    userId: 'user-002',
    bonusType: 'firstPurchase',
    amount: 1500,
    sourceUserId: 'user-006',
    sourceUserName: 'Pedro Alves',
    description: 'Bônus primeira compra - Compra de 15 cotas',
    level: 1,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-01T11:50:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    // Purchase on 2024-03-01; cutoff for '2024-03' is 2024-02-29 → after cutoff
    cutoffEligible: false,
  },
  {
    id: 'earn-003',
    userId: 'user-002',
    bonusType: 'repurchase',
    amount: 500,
    sourceUserId: 'user-008',
    sourceUserName: 'Roberto Mendes',
    description: 'Bônus recompra nível 2 - Compra de 5 cotas',
    level: 2,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-15T10:05:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    // Purchase on 2024-03-15; cutoff for '2024-03' is 2024-02-29 → after cutoff
    cutoffEligible: false,
  },
  {
    id: 'earn-004',
    userId: 'user-002',
    bonusType: 'team',
    amount: 1300,
    sourceUserId: null,
    sourceUserName: null,
    description: 'Bônus equipe mensal - 2% do total',
    level: 0,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-31T23:59:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: true, // closed at end-of-month, always eligible
  },
  {
    id: 'earn-005',
    userId: 'user-002',
    bonusType: 'leadership',
    amount: 1950,
    sourceUserId: null,
    sourceUserName: null,
    description: 'Bônus de liderança - Título Ouro',
    level: 0,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-31T23:59:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: true,
  },
  // User 002 - pending entry added AFTER the cutoff → will be paid next cycle
  {
    id: 'earn-006',
    userId: 'user-002',
    bonusType: 'repurchase',
    amount: 300,
    sourceUserId: 'user-009',
    sourceUserName: 'Fernanda Rocha',
    description: 'Bônus recompra nível 2 (compra após corte)',
    level: 2,
    referenceMonth: '2024-04',
    status: 'pending',
    createdAt: '2024-04-01T09:00:00Z',
    paidAt: null,
    // Created on 2024-04-01; cutoff for '2024-04' is 2024-03-31 → after cutoff
    cutoffEligible: false,
  },
  // User 003 - Maria Santos earnings
  {
    id: 'earn-007',
    userId: 'user-003',
    bonusType: 'firstPurchase',
    amount: 800,
    sourceUserId: 'user-007',
    sourceUserName: 'Lúcia Ferreira',
    description: 'Bônus primeira compra - Compra de 8 cotas',
    level: 1,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-05T16:35:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: false, // purchase on 2024-03-05, after cutoff 2024-02-29
  },
  {
    id: 'earn-008',
    userId: 'user-003',
    bonusType: 'team',
    amount: 600,
    sourceUserId: null,
    sourceUserName: null,
    description: 'Bônus equipe mensal - 2% do total',
    level: 0,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-31T23:59:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: true,
  },
  // User 001 - Admin earnings
  {
    id: 'earn-009',
    userId: 'user-001',
    bonusType: 'firstPurchase',
    amount: 5000,
    sourceUserId: 'user-002',
    sourceUserName: 'João Silva',
    description: 'Bônus primeira compra - Compra de 50 cotas',
    level: 1,
    referenceMonth: '2024-01',
    status: 'paid',
    createdAt: '2024-01-15T10:35:00Z',
    paidAt: '2024-02-15T10:00:00Z',
    cutoffEligible: false, // purchase on 2024-01-15, after cutoff 2023-12-31
  },
  {
    id: 'earn-010',
    userId: 'user-001',
    bonusType: 'repurchase',
    amount: 2500,
    sourceUserId: 'user-005',
    sourceUserName: 'Ana Costa',
    description: 'Bônus recompra nível 2',
    level: 2,
    referenceMonth: '2024-02',
    status: 'paid',
    createdAt: '2024-02-20T09:20:00Z',
    paidAt: '2024-03-15T10:00:00Z',
    cutoffEligible: false, // purchase on 2024-02-20, after cutoff 2024-01-31
  },
  {
    id: 'earn-011',
    userId: 'user-001',
    bonusType: 'dividend',
    amount: 7500,
    sourceUserId: null,
    sourceUserName: null,
    description: 'Dividendos - 20% lucro ÷ total cotas × suas cotas',
    level: 0,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-31T23:59:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: true,
  },
  {
    id: 'earn-012',
    userId: 'user-001',
    bonusType: 'team',
    amount: 1000,
    sourceUserId: null,
    sourceUserName: null,
    description: 'Bônus equipe mensal - 2% do total',
    level: 0,
    referenceMonth: '2024-03',
    status: 'paid',
    createdAt: '2024-03-31T23:59:00Z',
    paidAt: '2024-04-15T10:00:00Z',
    cutoffEligible: true,
  },
];

// Monthly summaries pre-calculated
export const mockMonthlySummaries: MonthlyEarningSummary[] = [
  {
    month: '2024-03',
    userId: 'user-002',
    firstPurchase: 1500,
    repurchase: 500,
    team: 1300,
    leadership: 1950,
    dividend: 0,
    total: 5250,
    lossProjection: 1200,
    networkEarnings: 5250, // 1500 + 500 + 1300 + 1950
    quotaEarnings: 0,
    cutoffDate: getCutoffDate('2024-03'), // 2024-02-29
  },
  {
    month: '2024-02',
    userId: 'user-002',
    firstPurchase: 2500,
    repurchase: 0,
    team: 1000,
    leadership: 0,
    dividend: 0,
    total: 3500,
    lossProjection: 0,
    networkEarnings: 3500,
    quotaEarnings: 0,
    cutoffDate: getCutoffDate('2024-02'), // 2024-01-31
  },
  {
    month: '2024-03',
    userId: 'user-003',
    firstPurchase: 800,
    repurchase: 0,
    team: 600,
    leadership: 0,
    dividend: 0,
    total: 1400,
    lossProjection: 400,
    networkEarnings: 1400,
    quotaEarnings: 0,
    cutoffDate: getCutoffDate('2024-03'),
  },
  {
    month: '2024-03',
    userId: 'user-001',
    firstPurchase: 3000,
    repurchase: 1500,
    team: 1000,
    leadership: 2500,
    dividend: 7500,
    total: 15500,
    lossProjection: 0,
    networkEarnings: 8000, // 3000 + 1500 + 1000 + 2500
    quotaEarnings: 7500,
    cutoffDate: getCutoffDate('2024-03'),
  },
];

// User overview
export const mockUserOverviews: UserEarningsOverview[] = [
  {
    userId: 'user-001',
    totalEarned: 250000,
    pendingEarnings: 0,
    thisMonthEarnings: 17500,
    lastMonthEarnings: 15200,
    averageMonthly: 20833,
    lossProjection: 0,
  },
  {
    userId: 'user-002',
    totalEarned: 85000,
    pendingEarnings: 300,
    thisMonthEarnings: 5250,
    lastMonthEarnings: 3500,
    averageMonthly: 7083,
    lossProjection: 1200,
  },
  {
    userId: 'user-003',
    totalEarned: 42000,
    pendingEarnings: 0,
    thisMonthEarnings: 1400,
    lastMonthEarnings: 1100,
    averageMonthly: 3500,
    lossProjection: 400,
  },
];

// Helper functions
export function getEarningsByUser(userId: string): EarningEntry[] {
  return mockEarnings.filter((e) => e.userId === userId);
}

export function getEarningsByMonth(userId: string, month: string): EarningEntry[] {
  return mockEarnings.filter((e) => e.userId === userId && e.referenceMonth === month);
}

export function getPendingEarnings(userId: string): EarningEntry[] {
  return mockEarnings.filter((e) => e.userId === userId && e.status === 'pending');
}

export function getMonthlySummary(userId: string, month: string): MonthlyEarningSummary | undefined {
  return mockMonthlySummaries.find((s) => s.userId === userId && s.month === month);
}

export function getUserOverview(userId: string): UserEarningsOverview | undefined {
  return mockUserOverviews.find((o) => o.userId === userId);
}

export function getEarningsByType(userId: string, bonusType: BonusType): EarningEntry[] {
  return mockEarnings.filter((e) => e.userId === userId && e.bonusType === bonusType);
}

export function calculateTotalByType(userId: string, bonusType: BonusType): number {
  return getEarningsByType(userId, bonusType).reduce((sum, e) => sum + e.amount, 0);
}
